export {
  VAULT_FOLDERS,
  DELETED_FOLDER,
  WRITABLE_FOLDERS,
  getVaultService,
  _resetVaultServiceCache,
  type VaultService,
  type VaultFolder,
  type CreateNoteInput,
  type CreateNoteResult,
  type ParsedNote,
  type MoveFileOptions,
  type MoveFileResult,
  type SoftDeleteResult,
  type FileMatch,
  type FileStat,
  type FindFilesOptions,
} from "./vaultService";
